### ISSUE TITLE
Annotation coordinates should be read as Longitude, Latitude

### ISSUE THREAD

**Issue by markpbaggett** [nakamura196/iiif_geo#1]
Hello,

This is a very interesting project you have.  I've been experimenting with it and noticed that point coordinates are ordered as Latitude, Longitude instead of Longitude, Latitude.  Since the Georeference Extension is adopting GeoJSON, I'm fairly sure the order should be Longitude, Latitude.

For example, from the examples in the specification, this is longitude, latitude to point at something in Rotterdam:

```
{
                "type": "Feature",
                "properties": {
                  "resourceCoords": [5085, 782]
                },
                "geometry": {
                  "type": "Point",
                  "coordinates": [4.4885839, 51.9101828]
                }
              },
```

This is a very cool project nonetheless and am excited to see future development.  😎 

https://nakamura196.github.io/iiif_geo/?u=https://raw.githubusercontent.com/markpbaggett/static_iiif/main/manifests/tests/map_canvas.json

**Comment by nakamura196** [comment]
Thank you for pointing out the issue with the coordinate ordering in our GeoJSON data. We appreciate your detailed feedback. We have corrected the latitude and longitude order to align with the GeoJSON standards.

Please let us know if there are any further issues or suggestions. Your contributions help us improve.
